mash-up-kr/mashup_Android

app/build.gradle
dependencies.gradle

- `dependencies.gradle`에 있는 minSdk,targetSdk, compileSdk 동작이 이뤄지지 않아 실행이 되지 않음
`Cause: compileSdkVersion is not specified. Please add it to build.gradle` 발생
- activityKtx 버전 "1.4.1" 를 불러올 수 없음
- activityKtx 버전은 1.4.0 이 최신이였음
- compileSdkVersion 에 들어갈 버전 변수를 저장 못하는 것으로 파악
- activityKtx 버전 "1.4.1"  을 "1.4.0" 으로 다운그레이드
-  minSdk,targetSdk, compileSdk  변수 제거 , 밖으로 꺼냄 
- https://developer.android.com/jetpack/androidx/releases/activity?hl=ko

fix: gradle setting

---

app/src/main/AndroidManifest.xml

- 앱 실행이 안됨
- 힐트 라이브러리 적용 후 메니페스트에 어플리케이션 태그를 등록하지 않음
- 메니페스트에 어플리케이션 태그를 추가

fix: 힐트오류, 메니페스트에 어플리케이션 태그 추가

---

app/src/main/java/com/mashup/data/datastore/UserDataSource.kt
app/src/main/java/com/mashup/data/dto/AttendanceCheckRequest.kt
app/src/main/java/com/mashup/data/dto/AttendanceCheckResponse.kt
app/src/main/java/com/mashup/data/repository/AttendanceRepository.kt
app/src/main/java/com/mashup/di/NetworkModule.kt
app/src/main/java/com/mashup/network/dao/AttendanceDao.kt
app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
app/src/main/java/com/mashup/ui/qrscan/QRScanViewModel.kt

close #64 
- 출석체크 API 연동
- memberId 로컬에 저장
- memberId 클라에서 관리 안해도 될것같긴함,, 흠
- 추후 성공 팝업 이미지 변경해야함

[Feature] 출석체크 API 연동

---

app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
app/src/main/java/com/mashup/ui/setting/SettingItem.kt
app/src/main/java/com/mashup/ui/setting/SettingScreen.kt
app/src/main/res/layout/activity_setting.xml
app/src/main/res/values/strings.xml
core/ui/src/main/java/com/mashup/core/ui/theme/Theme.kt

- 설정화면 Compose로 마이그레이션
참고
- 현재 로그인 정보가 없어 실제 에뮬레이터에 빌드에서 테스트해보려면 Manifest에서 SettingActivity를 main으로 설정하는게 편한 것 같아요!
|설정화면|
|---|
|<img src="https://user-images.githubusercontent.com/33657541/207379982-4ad717ae-25b6-4371-9704-0e4e150e0946.png " width="40%">|
close #154  🦕

[Feature] 설정화면 Setting Menu - Compose로 마이그레이션

---

app/build.gradle
app/src/main/java/com/mashup/ui/webview/WebViewActivity.kt
app/src/main/res/layout/activity_web_view.xml
dependencies.gradle

- compose webview로 migration 했습니다
- 페이지가 한개여서 canGoBack이 가능하던, 아니던 activity finish하게 했습니다
- 디바이더 그대로 옮겨서 잘보입니당
- 웹뷰 미웡~
- 뭔가...자바 8 지우다가 세팅이 덜돼서 ./gradlew 가 현재 안돼서 다음 pr부터 spotlesscheck + apply 하겠슴당 죄송..
|이전 화면|변경된 화면|
|---|---|
화면은 동일해서 첨부 안합니당 ㅎㅎ!!
close #156 🦕

🛠 webview -> compose webview migration

---

app/build.gradle
app/src/main/java/com/mashup/extensions/ModifierExt.kt
app/src/main/java/com/mashup/ui/model/SNSModel.kt
app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
app/src/main/java/com/mashup/ui/setting/sns/SNSItem.kt
app/src/main/java/com/mashup/ui/setting/sns/SNSListScreen.kt
app/src/main/res/layout/activity_setting.xml
core/common/src/main/res/values/styles.xml

- 설정화면 하단 SNS List Compose로 마이그레이션
- 그림자를 커스텀할 수 있는 확장함수 생성 및 적용
- 그림자 참고 : https://github.com/Debdutta-Panda/CustomShadow
close #153  🦕

[Feature] 설정화면 SNS List - Compose로 마이그레이션

---

app/src/main/java/com/mashup/network/interceptor/AuthInterceptor.kt

- API에서 토큰 만료 에러 코드 내려올 때 DataStore token 비워주기
close #161  🦕

[Fix] 토큰 만료일 때, 유저 정보 지워주기

---

core/ui/src/main/java/com/mashup/core/ui/typography/Typography.kt

- em : Typography 크기가 16sp라면 1em = 16sp
- 자간 -1%로 수정 : (-0.01).em
- Typography Preview 추가
|이전 화면|변경된 화면|
|---|---|
| <img src="https://user-images.githubusercontent.com/47407541/209418984-db38fd63-1bd5-4d09-892b-dc7f0ee6e420.jpeg " width="40%"> | <img src="https://user-images.githubusercontent.com/47407541/209418987-bda01bf3-fb09-476a-95ca-20cd30536507.jpeg " width="40%">|
|SNS 텍스트를 넣었는데 자간이 넘 좁았음|자간이 조~금 더 넓어짐 |
close #156 🦕

[Bug] Typograpy 설정해둔 것들 자간(letterSpacing) 수정

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
app/src/main/java/com/mashup/ui/setting/SettingScreen.kt
app/src/main/java/com/mashup/ui/setting/menu/SettingMenuItem.kt
app/src/main/java/com/mashup/ui/setting/menu/SettingMenuList.kt
app/src/main/java/com/mashup/ui/setting/sns/SNSList.kt
app/src/main/res/layout/activity_setting.xml

- 설정화면 전체 Composable 병합
|이전 화면|
|---|
|<img src="https://user-images.githubusercontent.com/33657541/209421751-f1fa4c97-2ae1-4ae7-807b-4ec1ee11a47b.png" width="50%">|
close #155  🦕

[Feature] 설정화면 Composable 합치기 

---

app/src/debug/google-services.json
app/src/main/java/com/mashup/base/BaseActivity.kt
app/src/main/java/com/mashup/data/repository/UserRepository.kt
app/src/main/java/com/mashup/ui/login/LoginActivity.kt
app/src/main/java/com/mashup/ui/splash/SplashActivity.kt
app/src/main/java/com/mashup/util/AnalyticsManager.kt

- AnalyticsManager를 Object로 변경
지난번 BaseActivity에 AnalyticsManager를 주입하여 개발했지만, 이후 GA를 추가하는 과정에서 Fragment에서도 필요하게 됨.
AnalyticsManager를 Fragment에 주입하자니 동일한 코드가 생기고 이후 BottomFragment 등 계속 늘어날 여지가 있어 object로 전역적으로 아무데서나 접근 가능하도록 변경
화면 변경 없음

[Refactoring] 🛠 AnalyticsManager object로 변경

---

app/src/main/java/com/mashup/ui/widget/MashUpButton.kt

- 기존에 xml로 제작된 ButtonView를 컴포즈로 마이그레이션
- ButtonView(xml) -> MashUpButton(compose)
변경된 화면은 없고 프리뷰 첨부합니다..
|ButtonCircularProgressbar|MashUpButton|
|---|---|
|<img width="161" src="https://user-images.githubusercontent.com/47407541/212346862-33c058bb-c40d-420a-b114-fb775bea6a08.png">|<img width="316" src="https://user-images.githubusercontent.com/47407541/212346848-63b2e492-4ca6-479c-83dc-30de67b10db8.png">|
close #191  🦕

[ReFactoring] ButtonView Compose로 마이그레이션

---

app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt

- FCM 알람 표시하기
- Android O(26) 이상부터는 NotificationChannel 생성
푸시 받았을 때 notification 뜰 수 있도록 기본적인 것들 우선 처리해뒀습니다..
서버에서 푸시 보내주는 형태나 기획상 정의 한 번 더 확인해봐야될 것 같긴해요..
|NotificationChannel |푸시 알림 왔을 때|
|---|---|
|<img src="https://user-images.githubusercontent.com/47407541/212104952-e297db27-2814-4b8a-8405-c03e4c470af1.jpeg">|<img src="https://user-images.githubusercontent.com/47407541/212104959-096e7b7a-9450-418b-b2b6-0dec31b5ce6e.jpeg" width="100%">|
close #182  🦕

[Feature] FCM 알람 표시하기

---

app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
app/src/main/java/com/mashup/ui/setting/SettingScreen.kt
app/src/main/java/com/mashup/ui/setting/menu/SettingMenuItem.kt
app/src/main/java/com/mashup/ui/setting/menu/SettingMenuList.kt
app/src/main/java/com/mashup/ui/widget/MashUpSwitch.kt

- MashSwitch UI 추가
- Material, Material3에서 제공해주는 Switch는 width, height를 변경할 수 없어서.. Custom으로 만들었어요.
|Switch On|Switch Off|
|---|---|
|![image](https://user-images.githubusercontent.com/33657541/215276761-9e7bcccd-6f8c-482f-af67-99c76dca4597.png)|![image](https://user-images.githubusercontent.com/33657541/215276733-84959726-7069-403c-91a3-6205a6f4beec.png)|

[Feature] mashup Switch UI 추가

---

app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt

- 현재 포그라운드에서 받은 알림을 클릭하면 아무 동작도 하지 않았음.
- NotificationBuilder에 PendingIntent 추가(SplashActivity)
😵
close #228 🦕

[Feature] 푸시알림 클릭했을 때 앱으로 진입하도록 PendingIntent 추가

---

app/build.gradle
app/src/main/java/com/mashup/ui/attendance/platform/PlatformAttendanceViewModel.kt
app/src/test/java/com/mashup/PlatformAttendanceViewModelTest.kt
app/src/test/java/com/mashup/fake/FakeAttendanceDao.kt
app/src/test/java/com/mashup/util/CoroutineRule.kt

edc40156926c470f30a8ab2ccf03fc0ba60e7816 
🐛 일정 시작 전일 경우 플랫폼 출결 현황 화면 상단 notice에 "아직 일정 시작 전이에요." 안내 문구 추가
- eventNum: Int -> 각 1부, 2부를 나타내는 값
- isEnd: Boolean -> eventNum이 끝났는지 나타내는 값
- eventNum == 0인 경우: 아직 일정 시작 전이예요.
- isEnd == false: 출석체크가 실시간으로 진행되고 있어요
- eventNum == 1 && isEnd == true: 중간 집계 중이에요
- eventNum == 2 && isEnd == true: 출석체크가 완료되었어요
2dc0e6ee9d898b0db9f83208b1f3373be75617b7
🍰 플랫폼 출결 현황 화면의 상단 notice 문구를 결정하는 로직에 대한 테스트 케이스 추가
close #235 🦕

[Bug] 플랫폼 출결 현황 "일정 시작 전 문구 표시"

---

app/src/test/java/com/mashup/PlatformAttendanceViewModelTest.kt

- ViewModel을 생성할 때 주입하는 Fake 객체들을 매번 테스트마다 새로 생성하고 있어서, @Before 어노테이션을 활용해 중복되는 코드들을 정리
- @Before : Test 메소드가 실행되기 전 항상 실행된다. 공통적으로 환경을 구축하는 코드를 넣어주면 된다.
close #246  🦕

[Refactoring] PlatformAttendanceViewModelTest 중복코드 정리

---

feature/setting/src/androidTest/java/com/mashup/feature/SettingScreenTest.kt
feature/setting/src/main/java/com/mashup/feature/SettingScreen.kt
feature/setting/src/main/java/com/mashup/feature/sns/SNSList.kt

- https://developer.android.com/reference/kotlin/androidx/compose/foundation/package-summary#LocalOverscrollConfiguration()
- LocalOverscrollConfiguration: Composition local to provide configuration for scrolling containers down the hierarchy. null means there will be no overscroll at all.
화면은 동일하지만 SNSList부분을 스크롤해보면 띠용거리던게(scroll effect)가 사라져있어야 함..
close #164  🦕

[Feature] 컴포즈 LazyLayout을 스크롤 할 때 생기는 overScroll effect 없애기

---

app/src/main/java/com/mashup/ui/model/AttendanceModel.kt

- 현재 기본 출석의 경우 api response에 scheduleName이 null으로 오는데, 이 경우 `날짜`만 표시되어야 하는데 `날짜 | ` 이렇게 구분선이 UI에 함께 보여짐
- scheduleName에 null이 들어오면 | 없도록 맵핑 로직 수정
|이전 화면|변경된 화면|
|---|---|
|<img width="50%" src="https://user-images.githubusercontent.com/47407541/223119594-0a8d5adb-1d53-4177-965f-56ee9ac0f650.jpeg"/>|<img width="50%" src="https://user-images.githubusercontent.com/47407541/223119609-95df48ac-7772-4763-8f22-44eadf07cf76.jpeg"/>|
close #250  🦕

[Bug] 마이페이지 ScheduleName null 일때 UI 변경

---

app/src/main/AndroidManifest.xml

- 카메라 화면에서 인터넷 연결이 안되어 있을 때..  인터넷 연결 끊킴 화면이 여러번 Task에 쌓이는 오류 수정
화면 변경 없음
close #263  🦕

[Fix] 인터넷 연결 끊김 화면 singleTop으로 변경 (#263)

---

app/build.gradle
app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
core/ui/src/main/java/com/mashup/core/ui/widget/MashupToolbar.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeContent.kt
feature/setting/src/androidTest/java/com/mashup/feature/SettingScreenTest.kt

- UI 작업하기 편하도록 당근 흔들기(DanggnShakeContent), 당근 랭킹(DanggnRankingContent) 컴포저블을 각각 생성
- 당근 흔들기(민지): DanggnShakeContent
- 당근 랭킹(석주): DanggnRankingContent
- MashUpToolbar 오른쪽 버튼을 확장성있게 사용할 수 있도록 수정
- 항상 close('X') 버튼을 사용하는게 아니라 도움말('?') 등 다른 버튼을 사용할 수도 있어서 확장성있게 수정
- 네이밍 closeButton에서 actionButton으로 변경
- 우측 버튼의 Drawable Res 기본 값은 'X'아이콘 유지
close #282  🦕

[Feature] 당근 흔들기(DanggnShakeContent), 당근 랭킹(DanggnRankingContent) 컴포저블 각각 생성

---

feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnViewModel.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/data/DanggnDao.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnRandomTodayMessageResponse.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeContent.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/shake/RandomTodayMessage.kt

- [GET] /api/v1/danggn/random-today-message api 추가
- 오늘의 랜덤 하소연 UI 추가
- (UI가 너무 간단해서 커밋 분리를 못했네.. 미안합니다 ^^-)
close #296  🦕

[Feature] 오늘의 랜덤 하소연(메시지) 기능 추가

---

core/ui/build.gradle
core/ui/src/main/java/com/mashup/core/ui/widget/TabRow.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt

- Material 제공해주는 TabRow는 무조건 fillMaxWidth라서 WrapContent 되도록 Custom tab을 만들었어요. 
|이전 화면|변경된 화면|
|---|---|
|<img src="https://user-images.githubusercontent.com/33657541/236678592-37ef1fe4-8981-4fb4-ad82-97ed70807deb.png" width="400">|<img src="https://user-images.githubusercontent.com/33657541/236678614-4612a360-f15b-45a2-8fa4-24b06051273b.png" width="400">|
close #341  🦕

[Feature] 디자인에 맞게 TabRow 수정

---

feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt

- 백그라운드 당근 흔들기랑 맞췄슴다
|이전 화면|변경된 화면|
|---|---|
|![image](https://user-images.githubusercontent.com/67602108/236687840-a32b4774-17fe-495e-876f-ffe6b56b16b1.png)|![image](https://user-images.githubusercontent.com/67602108/236687801-15fdf524-0791-4e99-960d-cbafe329697b.png)|

[fix] 백그라운드컬러 당근 흔들기랑 통일

---

app/src/main/java/com/mashup/ui/main/popup/MainBottomPopup.kt

- 버튼 목록 Row에 bottomPadding 24 + Content를 감싸는 Column에 bottomPadding 20이 합쳐져서 총 44의 padding이 들어가있는 것 같음. (피그마에는 24)
|이전 화면|변경된 화면|
|---|---|
|<img src="https://github.com/mash-up-kr/mashup_Android/assets/47407541/18d556ad-d079-4042-b837-677a6af30454" width="300"/>|<img src="https://github.com/mash-up-kr/mashup_Android/assets/47407541/70fcac69-d90d-4b4c-8f51-fab90da4c9a0" width="300"/>|
~~확인부터 받아야 될 것 같아서 따로 이슈로 따진않음~~

🛠 padding 중복으로 적용되어 있어서 하나 제거

---

app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt

- '당근 흔들기 알림' 토글을 동작하면 '매시업 소식 알림' 토글이 함께 동작했다.
- 각각 동작하도록 수정
- 
|이전 화면|변경된 화면|
|---|---|
|https://github.com/mash-up-kr/mashup_Android/assets/47407541/14f50a85-1b0f-4ac3-b5d3-120e636e02c8|https://github.com/mash-up-kr/mashup_Android/assets/47407541/04841962-9a7a-476d-bb41-9be8e45df9a1|

[Fix] 푸시알림 토글 동작 수정

---

feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt

- 미리 11등으로 짜른 뒤에 찾아서 못찾아서 못그리고 있었습니다~
- take(11) 로 표시해주고, 전체 등수를 넘겨서 id로 찾습니다~
- 근데? 11개보다 적을 때 EMPTY_RANKING도 추가하는 로직을 추가했습니다~
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://github.com/mash-up-kr/mashup_Android/assets/67602108/d2e95414-3cca-46ab-b771-b76e7d69c7db)|

[fix] 내 등수 표기 완료

---

feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnViewModel.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnGameController.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnMode.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnModeController.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeEffect.kt

- 카운트다운 로직 DanggnGameController로 이동
- FeverTime CountDown 뷰 그리는 로직도 수정했어요! (기존에는 else를 3 이미지로 처리했기 떄문에 '3 -> 2 -> 1 -> 0'으로 카운트다운 됐을 때 이미지가 '3 -> 2 -> 1 -> 3 -> 피버타임 꺼짐' 이렇게 작동하고 있었어요..ㅎㅎ)
close #323  🦕

[Feature] 피버 타임 카운트다운 리팩토링

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mashup/ui/danggn/DanggnUpdateActivity.kt
app/src/main/java/com/mashup/ui/main/MainActivity.kt
core/common/src/main/java/com/mashup/core/common/model/ActivityEnterType.kt
core/ui/src/main/java/com/mashup/core/ui/widget/MashupToolbar.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ui/DanggnUpdateScreen.kt
feature/danggn/src/main/res/values/strings.xml

- 당근 흔들기 업데이트 설명 UI 구현
- Description은 아직 확정이 안된 것 같아서 머지는 안하고 있을게요!
|이전 화면|변경된 화면|
|---|---|
|none|![image](https://github.com/mash-up-kr/mashup_Android/assets/33657541/f9fcafa0-b238-449e-8702-cde7617ca4b6)|
close #395  🦕

[Feature] 당근 흔들기 업데이트 설명 UI 구현

---

feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt

- sample
추가한 인원만큼 보일 예정.
근데, 중요한 점이 있음....
lazy column으로 변경하니 scrollTo(0)가 안먹음 (item click이 안되는데, 해결방법 아시는분~)
- figma link
:
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://github.com/mash-up-kr/mashup_Android/assets/67602108/29711101-cbba-4b29-b08e-aea3ebdfde87)|

[feat] lazy column으로 변경 + 매시업 전체 인원 보여주기 (11명 이상)

---

app/src/main/java/com/mashup/ui/danggn/DanggnUpdateActivity.kt
app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnInfoScreen.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ui/DanggnUpdateScreen.kt

- 당근 업데이트 설명 화면, 당근 내에서 진입 시 하단 버튼 제거
- figma link
: 피그마 링크는 없네용 ㅜㅜ
|이전 화면|변경된 화면|
|---|---|
|input your previous image|<img src="https://github.com/mash-up-kr/mashup_Android/assets/33657541/df32ed91-112b-4611-8a2a-20b30ead56e2" width="40%">|

🧸 당근화면에서 진입 시 하단 버튼 사라지게 하기

---

app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardContent.kt

- 코멘트 등록할 때 roundId가 아닌 rewardId를 사용하도록 변경

[FIX] 코멘트 등록할 때 roundId가 아닌 rewardId를 사용하도록 변경

---

feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt

- 이전 회차 1등 여부를 firstPlaceState에서 분리

[FIX] member-popups api 너무 많이 호출하던 문제 해결
