- app/build.gradle
- build.gradle
- dependencies.gradle
close #2 
어나니머쓱 팀 코드를 보고 많이 참고해서 dependencies 버전들을 분리해보았어
(준비형 짱)
> dependencies.gradle 생성 및 이미지, 네트워크 의존성 추가

- app/build.gradle
- app/src/main/java/com/mashup/MainActivity.kt
- app/src/main/java/com/mashup/MashUpApplication.kt
- app/src/main/java/com/mashup/di/NetworkModule.kt
- app/src/main/java/com/mashup/di/RepositoryModule.kt
- build.gradle
- dependencies.gradle
close #1 
google Hilt 기본 적용 PR입니다.
dependencies PR이 선 병합이 되어야 합니다.
> Hilt 라이브러리 적용

- app/build.gradle
- app/src/main/java/com/mashup/di/NetworkModule.kt
- app/src/main/java/com/mashup/network/interceptor/AuthInterceptor.kt
- dependencies.gradle
close #18 
- 다버그일때만 logging 추가하기
- retorift di 작성
> [Feature] Retorift 초기 설정

- app/src/main/java/com/mashup/widget/QRScanRectView.kt
- app/src/main/res/layout/fragment_qr_scan.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
close #20 
- QR Scan 인식하는 사각형 영역 UI Widget 구현
- 각 Scan 모서리는 추후 디자인 확정되면 구현할 예정!
> [Feature] QR Scan 인식 화면 UI 구현

- .idea/deploymentTargetDropDown.xml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mashup/extensions/ContextExt.kt
- app/src/main/java/com/mashup/extensions/FragmentExt.kt
- app/src/main/java/com/mashup/extensions/UIExt.kt
- app/src/main/java/com/mashup/extensions/ViewExt.kt
- app/src/main/java/com/mashup/ui/main/MainActivity.kt
- app/src/main/java/com/mashup/ui/main/MainType.kt
- app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
- app/src/main/java/com/mashup/widget/QRScanRectView.kt
- app/src/main/res/drawable/bg_qrcode_sacn_boundray.xml
- app/src/main/res/drawable/ic_bg_camera_btn.xml
- app/src/main/res/drawable/ic_qrscan_tab.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_qr_scan.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/themes.xml
> [Feature] QRCode UI 개선 + Activity로 변경

- app/src/main/java/com/mashup/di/NetworkModule.kt
- app/src/main/java/com/mashup/network/interceptor/AuthInterceptor.kt
close #54 
- token authInterceptor 재 추가
> [Feature] network interceptor

- app/src/main/java/com/mashup/common/Validation.kt
- app/src/main/java/com/mashup/data/dto/AccessResponse.kt
- app/src/main/java/com/mashup/data/repository/MemberRepository.kt
- app/src/main/java/com/mashup/network/dao/MemberDao.kt
- app/src/main/java/com/mashup/ui/extensions/TextFieldExt.kt
- app/src/main/java/com/mashup/ui/login/LoginActivity.kt
- app/src/main/java/com/mashup/ui/login/LoginViewModel.kt
- app/src/main/java/com/mashup/ui/signup/SignUpValidation.kt
- app/src/main/java/com/mashup/ui/signup/SignUpViewModel.kt
- app/src/main/java/com/mashup/ui/signup/fragment/SignUpAuthFragment.kt
- app/src/main/java/com/mashup/ui/signup/fragment/SignUpCodeFragment.kt
- app/src/main/java/com/mashup/ui/signup/state/AuthState.kt
- app/src/main/java/com/mashup/ui/signup/state/CodeState.kt
- app/src/main/res/layout/activity_login.xml
- app/src/test/java/com/mashup/SignInValidationTest.kt
close #66 
- loginAPI DTO 수정
- id, pwd 다 입력해야 button enabled 처리
- pwd textInputType 지정
> [Feature] 로그인 API DTO 수정

- app/src/main/java/com/mashup/base/BaseActivity.kt
- app/src/main/java/com/mashup/base/BaseFragment.kt
- app/src/main/java/com/mashup/ui/attendance/crew/CrewAttendanceActivity.kt
- app/src/main/java/com/mashup/ui/attendance/crew/CrewAttendanceViewModel.kt
- app/src/main/java/com/mashup/ui/attendance/platform/PlatformAttendanceActivity.kt
- app/src/main/java/com/mashup/ui/attendance/platform/PlatformAttendanceViewModel.kt
- app/src/main/java/com/mashup/ui/login/LoginActivity.kt
- app/src/main/java/com/mashup/ui/login/LoginViewModel.kt
- app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
- app/src/main/java/com/mashup/ui/qrscan/QRScanViewModel.kt
- app/src/main/java/com/mashup/ui/signup/SignUpViewModel.kt
- app/src/main/java/com/mashup/ui/signup/fragment/SignUpCodeFragment.kt
- app/src/main/java/com/mashup/utils/ProgressbarUtil.kt
- app/src/main/res/values/styles.xml
> [Feature] API 호출 시 로딩 추가

- app/src/main/java/com/mashup/ui/model/AttendanceModel.kt
- app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
> mypage viewmodel 리펙터링

- app/src/main/java/com/mashup/data/model/MemberInfo.kt
- app/src/main/java/com/mashup/ui/attendance/crew/CrewListItem.kt
- app/src/main/java/com/mashup/ui/attendance/platform/AttendanceNoticeItem.kt
- app/src/main/java/com/mashup/ui/attendance/platform/PlatformListItem.kt
- app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
- app/src/main/java/com/mashup/ui/schedule/adapter/ScheduleViewHolder.kt
- app/src/main/res/drawable/bg_common_dialog_20.xml
- app/src/main/res/layout/item_end_schedule.xml
- app/src/main/res/layout/item_inprogress_schedule.xml
close #109 
- shadow border 추가하기
> [Refactoring] shadow 빼기

- app/src/main/res/layout/bottom_sheet_attendance_info.xml
- app/src/main/res/values/strings.xml
close #116 
- 점수 반영 조건 수정 됨
- 출석 점수 제도가 자주 변경될 요지가 있어 추후 WebView로 수정될 예정
> [Feature] 🛠 점수 획득 케이스 수정

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> 🧸 github 템플릿 추가

- app/src/main/java/com/mashup/ui/signup/fragment/SignUpMemberFragment.kt
- Unknown 기본값이 들어가있는 에러 해결
|이전 화면|변경된 화면|
|---|---|
|<img src="https://user-images.githubusercontent.com/33657541/196675958-dc04b787-16ec-4c48-9207-c1ab3c133910.png" width="60%">|<img src="https://user-images.githubusercontent.com/33657541/196676325-203e6551-714c-4e13-814a-0f92c7f00dd5.png" width="60%">|
close #129 🦕
> 🐛회원가입 단계에서 Unknown으로 노출되는 현상 해결(#129)

- app/build.gradle
- app/src/main/AndroidManifest.xml
> 🐛 lint 실패하는 이슈 수정 (#144)

- app/src/main/java/com/mashup/ui/attendance/crew/CrewAttendanceActivity.kt
- app/src/main/java/com/mashup/ui/attendance/platform/AttendanceNoticeItem.kt
- app/src/main/java/com/mashup/ui/attendance/platform/AttendanceSeminarItem.kt
- app/src/main/java/com/mashup/ui/attendance/platform/PlatformListItem.kt
- app/src/main/java/com/mashup/ui/main/MainActivity.kt
- app/src/main/java/com/mashup/ui/mypage/AttendanceType.kt
- app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
- app/src/main/java/com/mashup/ui/qrscan/CongratsAttendanceScreen.kt
- app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
- app/src/main/java/com/mashup/ui/schedule/adapter/ScheduleViewHolder.kt
- app/src/main/java/com/mashup/ui/signup/dialog/platform/PlatformAdapter.kt
- app/src/main/java/com/mashup/ui/signup/dialog/term/TermsAgreementDialog.kt
- app/src/main/java/com/mashup/ui/splash/SplashActivity.kt
- app/src/main/java/com/mashup/ui/webview/WebViewActivity.kt
- app/src/main/java/com/mashup/util/DesignUtil.kt
- core/ui/src/main/java/com/mashup/core/ui/typography/Typography.kt
- gradle.properties
> [Feature] 빌드 속도 개선

- app/build.gradle
- app/src/debug/google-services.json
- app/src/main/AndroidManifest.xml
- app/src/main/res/values/strings.xml
- debug와 release 앱 분리하기
|이전 화면|변경된 화면|
|---|---|
|none|![image](https://user-images.githubusercontent.com/33657541/201471226-65bdbdc6-bb26-46fb-8ef4-69bac38f12ea.png)|
close #147 🦕
> [Feature] 디버그, 릴리즈 분리하기

- .github/workflows/lint_check.yml
lint check ci 추가입니다, pr 시에만 lint check를 돌게 만들었습니다
close #141  🦕
> Lint Check CI

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mashup/base/BaseActivity.kt
- app/src/main/java/com/mashup/util/AnalyticsManager.kt
- Firebase GA 설정
- Compose에서는 어떻게 구조를 가져가면 좋을지 고민해봐야 할 듯..
> 🧸 firebase analytics 초기 설정(#113)

- app/src/main/java/com/mashup/base/BaseActivity.kt
- app/src/main/java/com/mashup/constant/UserActionLogs.kt
- app/src/main/java/com/mashup/ui/login/LoginActivity.kt
- app/src/main/res/layout/activity_login.xml
> [Feature] 로그인, 회원가입 화면 로그 추가

- app/src/main/java/com/mashup/data/datastore/UserDataSource.kt
- app/src/main/java/com/mashup/data/repository/UserRepository.kt
- app/src/main/java/com/mashup/network/interceptor/AuthInterceptor.kt
- app/src/main/java/com/mashup/ui/login/LoginActivity.kt
- app/src/main/java/com/mashup/ui/login/LoginViewModel.kt
- app/src/main/java/com/mashup/ui/main/MainViewModel.kt
- app/src/main/java/com/mashup/ui/schedule/ScheduleViewModel.kt
- app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
- app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt
- app/src/main/java/com/mashup/ui/signup/SignUpViewModel.kt
- app/src/main/java/com/mashup/ui/withdrawl/WithdrawalActivity.kt
- app/src/main/java/com/mashup/ui/withdrawl/WithdrawalViewModel.kt
- app/src/main/java/com/mashup/util/AnalyticsManager.kt
- UserRepository로 유저 데이터 접근하도록 수정
- 로그아웃, 회원 탈퇴 시 토큰 지우기 
동일
close #172  🦕
> [Fix] 로그아웃, 회원탈퇴 시 유저 데이터 Clear

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt
- firebase fcm sdk 추가
- FirebaseMessagingService 매니페스트에 등록
화면 변경없음!
close #121 🦕
> [Feature] firebase fcm 초기 설정

- app/src/main/java/com/mashup/constant/UserActionLogs.kt
- app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
- app/src/main/java/com/mashup/ui/withdrawl/WithdrawalActivity.kt
- sample
|이전 화면|변경된 화면|
|---|---|
close #177  🦕
> [Refactoring] QR Code GA Logging

- app/src/main/java/com/mashup/constant/UserActionLogs.kt
- app/src/main/java/com/mashup/ui/signup/SignUpActivity.kt
- 회원가입 화면 GA 추가
변경된 화면 없음
close #179  🦕
>  [Feature] 회원가입 GA 추가

- app/src/main/java/com/mashup/data/datastore/UserDataSource.kt
- app/src/main/java/com/mashup/data/dto/LoginRequest.kt
- app/src/main/java/com/mashup/data/repository/MemberRepository.kt
- app/src/main/java/com/mashup/data/repository/UserRepository.kt
- app/src/main/java/com/mashup/ui/login/LoginViewModel.kt
- app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt
- 로그인할 때, fcm 토큰 전달하기
- 화면 변경 없음
> [Feature] 로그인 할 때 Fcm Token 전달하기

- app/src/main/java/com/mashup/constant/log/UserActionKeys.kt
- app/src/main/java/com/mashup/constant/log/UserActionLogs.kt
- app/src/main/java/com/mashup/ui/login/LoginActivity.kt
- app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
- app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
- app/src/main/java/com/mashup/ui/signup/SignUpActivity.kt
- app/src/main/java/com/mashup/ui/withdrawl/WithdrawalActivity.kt
- 회원가입 플로우에서 뒤로가기, 닫기에 대한 GA 추가했어요!
화면 변경 없음
close #189  🦕
> [Feature] signup 화면에서 close, back ga 추가

- app/src/main/java/com/mashup/data/dto/ContentResponse.kt
- app/src/main/java/com/mashup/data/dto/EventResponse.kt
- app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailViewModel.kt
- Schedule API 파싱 오류 해결
|이전 화면|변경된 화면|
|---|---|
|빈 화면 + 오류 메세지|<img src="https://user-images.githubusercontent.com/33657541/213485320-9f77bfd2-950f-47f5-a04c-445fec5cce9a.png" width="40%">|
> [Fix] Home 화면 Schedule List 파싱 오류 해결

- app/src/main/java/com/mashup/data/datastore/UserDataSource.kt
- app/src/main/java/com/mashup/data/dto/SignUpRequest.kt
- app/src/main/java/com/mashup/data/repository/FirebaseRepository.kt
- app/src/main/java/com/mashup/data/repository/MemberRepository.kt
- app/src/main/java/com/mashup/data/repository/UserRepository.kt
- app/src/main/java/com/mashup/ui/login/LoginViewModel.kt
- app/src/main/java/com/mashup/ui/signup/SignUpViewModel.kt
- app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt
- 회원 가입 시 FcmToken 전달
- fcmToken callback 형태로 가져오기
화면 변경없음
close #181  🦕
> [Feauture] 회원가입 시 fcm Token 전달하기 & token 가져오는 로직 수정

- app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt
-  FCM 알람에 이미지가 있을 경우 보여질 수 있도록 기능 추가
* 백그라운드는 별도의 처리가 없어도 됨
close #200 🦕
> [Feature] FCM 알람에 이미지도 보여질 수 있도록 기능 추가

- app/src/main/java/com/mashup/data/dto/PushNotificationRequest.kt
- app/src/main/java/com/mashup/data/repository/MemberRepository.kt
- app/src/main/java/com/mashup/network/dao/MemberDao.kt
- app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt
- 푸시알림 수신 여부 설정하는 API 연결
화면 없음
> [Feature] 푸시알림 수신 여부 설정하는 API 연결

- core/common/src/main/java/com/mashup/core/common/widget/TextFieldView.kt
-  아이디 입력했을 때 Suggestion 영역 제거
|이전 화면|변경된 화면|
|---|---|
|<img src="https://user-images.githubusercontent.com/33657541/215286202-77ca90d3-7db2-40ee-b8a6-7acf69f3211b.png" width="30%">|![image](https://user-images.githubusercontent.com/33657541/215286232-156722e5-7289-4224-a3a3-7db92730262e.png)|
close #130  🦕
> [Fix] 아이디 입력할 때 자동 입력 필드 제거

- app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
- app/src/main/java/com/mashup/ui/setting/menu/SettingMenuItem.kt
- 푸시 알림 설정하는 토글에 클릭이벤트 연결
설정화면 토글 클릭하면 바뀌어유
close #206  🦕
> 🧸 푸시 알림 설정하는 토글에 클릭이벤트 연결

- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/fragment_sign_up_code.xml
- core/common/src/main/java/com/mashup/core/common/widget/TextFieldView.kt
- 키보드 올리기 성공~!
- 매니페스트 빼면 안올라옵니다
|이전 화면|변경된 화면|
|---|---|
화면 캡쳐는 못했습니당
close #214  🦕
> 🐛 포커스 줘서 키보드 올리기

- app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
- app/src/main/java/com/mashup/ui/schedule/ScheduleViewModel.kt
- 스케줄 조회 한번만 하기
화면 변경 없음
close #215  🦕
> [Bug] 스케줄 조회 한번만 하기

- app/src/main/java/com/mashup/ui/signup/SignUpValidation.kt
- app/src/main/res/layout/fragment_sign_up_auth.xml
- 기존 규칙: 영문, 숫자를 조합하여 8자 이상
- 변경 규칙: 영문, 숫자, 특수문자를 조합하여 8자 이상
- 문구 변경
- 특수문자 입력 가능
close #217  🦕
> [Feature] 비밀번호 정규식 조건에 특수문자 추가(@$!%^#*?&) 및 가이드 문구 수정

- app/src/main/java/com/mashup/ui/signup/SignUpValidation.kt
- app/src/main/java/com/mashup/ui/signup/fragment/auth/SignUpAuthFragment.kt
- app/src/main/res/values/strings.xml
- ID 숫자 포함 입력할 수 있게 연결
|이전 화면|변경된 화면|
|---|---|
|input your previous image|<img src="https://user-images.githubusercontent.com/33657541/217545323-6d5c28a7-bf3a-42c1-b832-41755edde10c.png" width="40%">|
close #216  🦕
> [Feature] ID 정규식 수정

- app/src/main/java/com/mashup/ui/main/MainViewModel.kt
- app/src/main/java/com/mashup/ui/qrscan/CongratsAttendanceScreen.kt
- 출석 성공 시 뜨는 UI를 변경했어요.
- ~디자인 가이드 상 회색 투명도가  전체 화면을 덮는 것이 맞지만.. 상태바 너머로 표시되지 안되는 문제가 있었어요.~
- ~windowInset을 만져야 하는데 시간이 부족해 우선 회색 배경을 빼기로 했어요~
- 출석 성공 UI 표시되는 애니메이션이 이상했어요.
화면 변경없음
close #223  🦕
> [Fix] 출석 성공 UI 수정

- app/src/main/res/layout/item_end_schedule.xml
- app/src/main/res/layout/item_inprogress_schedule.xml
> [Refactoring] 스케줄 카드 UI 수정

- app/src/main/java/com/mashup/data/model/ScoreDetails.kt
- app/src/main/java/com/mashup/ui/model/AttendanceModel.kt
- app/src/main/java/com/mashup/ui/mypage/AttendanceListAdapter.kt
- app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
- app/src/main/res/layout/item_mypage_attendance_history_list.xml
- core/common/src/main/java/com/mashup/core/common/extensions/TextViewExt.kt
- 마이페이지 취소 선 제거
|이전 화면|변경된 화면|
|---|---|
|![image](https://user-images.githubusercontent.com/33657541/218125465-ca534437-155b-46b2-b350-3a23a9ba4704.png)|![image](https://user-images.githubusercontent.com/33657541/218125498-54dc6a64-b2d6-4e04-a8f9-47a192a0d331.png)|
close #230  🦕
> [Fix] mypage history 취소선 제거

- app/src/main/java/com/mashup/ui/schedule/adapter/ScheduleViewHolder.kt
- 출석현황 리스트 버튼 보여주는 로직 조건 변경
dataCount 로 출석현황 보여주는 로직은 이상하다!
close #232  🦕
> [Refactoring] 출석현황 리스트 버튼 보여주는 로직 조건 변경

- app/src/main/java/com/mashup/ui/main/MainActivity.kt
- app/src/main/java/com/mashup/ui/main/MainViewModel.kt
- app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
- app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
- QR 스캔하면 스케줄 리스트 갱신하기
화면 변경 없음
close #227  🦕
> [Fix] QR 인식하면 Result Code 내려주고 스케줄 갱신하기

- app/build.gradle
- github ci
- Setting Compose로 마이그레이션
> 🌱 release/v1.1.0

- app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
- core/common/src/main/res/values/colors.xml
- scanner statusbar 확장입니다~
- 제가 체크 했을 땐 이상 없긴 했는데 혹시나 다른 페이지도 이상 없는지 "같이" 확인 해주실분 ^^!!!
|이전 화면|변경된 화면|
|---|---|
|![image](https://user-images.githubusercontent.com/67602108/219260510-9e5810c8-1005-437a-a95f-c0f373a60a1b.png)|![image](https://user-images.githubusercontent.com/67602108/219260674-fdfbf752-9cc3-4f1b-b148-52d54e6cdbf4.png)|
> 🧸 QR Scanner status bar 확장 (#237)

- app/src/main/java/com/mashup/data/model/ScoreDetails.kt
- app/src/main/java/com/mashup/ui/model/AttendanceModel.kt
- history Response nullable로 수정
화면 변경 없음
close #238  🦕
> [Fix] mypage history scheduleName nullable 처리하기

- app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
> [Fix] 테스트로 추가된 코드 제거

- app/src/main/AndroidManifest.xml
- dependencies.gradle
- manifest 수정 + minSdk 23 -> 24
|이전 화면|변경된 화면|
|---|---|
이미지 변경은 아니라서 ㅎㅎ;;
막아버렸습니다... 
close #252  🦕
> [#252] 멀티 윈도우 막기

- app/src/main/res/layout/item_event_timeline_content.xml
- 스케줄 이벤트 리스트 여러 줄로 늘어날 수 있도록 수정
|이전 화면|변경된 화면|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/33657541/223126183-9552397b-76a7-4d74-987d-e15a31047477.png" width="200">|<img src="https://user-images.githubusercontent.com/33657541/223126402-cfa74c6c-0f4f-4c70-8b3d-19c0c78bfe8d.png">|
close #251  🦕
> [Fix] 스케줄 이벤트 리스트 여러줄로 늘어날 수 있도록 수정

- app/src/main/res/values/strings.xml
- sample
|이전 화면|변경된 화면|
|---|---|
||<img width="353" alt="image" src="https://user-images.githubusercontent.com/67602108/227759720-7d0c0e26-439a-4330-a369-b2e1612affb0.png">|
> [Fix] 줄바꿈 적용입니다

- app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
- app/src/main/java/com/mashup/ui/schedule/ScheduleViewModel.kt
- app/src/main/res/layout/fragment_schedule.xml
- app/src/main/res/values/strings.xml
- 다음 세미나가 등록 되어있지 않고, 기수가 진행중일 때 텍스트 추가 및 refresh 버튼 제거
|이전 화면|변경된 화면|
|---|---|
||<img width="380" alt="image" src="https://user-images.githubusercontent.com/67602108/227761341-db30dc6b-0c43-4b85-868f-061dd8478cfd.png">|
> [Feature] 텍스트 수정 및 버튼 제거

- app/build.gradle
작업 내역
릴리즈 v1.1.4
업데이트 유도 기능
스케줄 리스트 타이틀 문구 수정
> [Release] version 1.1.4

- app/src/main/java/com/mashup/data/dto/AccessResponse.kt
- app/src/main/java/com/mashup/data/dto/MemberInfoResponse.kt
- app/src/main/java/com/mashup/data/dto/PushNotificationRequest.kt
- app/src/main/java/com/mashup/data/repository/MemberRepository.kt
- app/src/main/java/com/mashup/ui/main/MainViewModel.kt
- app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
- app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt
- core/datastore/src/main/java/com/mashup/datastore/data/repository/UserPreferenceRepository.kt
- core/model/src/main/java/com/mashup/core/model/data/local/UserPreference.kt
- 로그인, 회원가입, 회원 정보 당근 푸시 동의 여부 필드 추가
화면 변경 없음
close #288  🦕
> [Feature] danggnPush Field 추가하기

- app/src/main/java/com/mashup/di/NetworkModule.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnScoreRequest.kt
-  danggn score Body로 DanggnScoreRequest 객체가 변환이 안되던 문제 수정
화면 변경 없음
close #287  🦕
> [Fix] danggn score api 안되던 문제 수정

- feature/danggn/src/main/java/com/mashup/feature/danggn/data/DanggnDao.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnAllMemberRankResponse.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
- 당근 개인 랭킹 사용 안하기로 합의가 되어 전체랭킹(ALL만 사용합니다)
화면 변경 없음!
> [refactoring] 당근 API Response 수정

- app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
- app/src/test/java/com/mashup/PlatformAttendanceViewModelTest.kt
- app/src/test/java/com/mashup/fake/FakeDanggnDao.kt
- app/src/test/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModelTest.kt
- app/src/test/java/com/mashup/util/CoroutineRule.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- ranking viewModel 연결했습니다
- test code "처음으로 ^^" 짰습니다
화면은 그대로예요
> [feature] ranking ui viewModel 연결

- core/common/src/main/java/com/mashup/core/common/utils/DecimalUtil.kt
- core/ui/src/main/java/com/mashup/core/ui/colors/BrandColor.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
- 내 랭킹 추가
- 아무도 흔들지 않았을 때 텍스트 추가했습니다
|이전 화면|변경된 화면|
|---|---|
|![image](https://user-images.githubusercontent.com/67602108/235362418-aaff38ff-d5b9-4e64-ab7a-3ccd007920d2.png)|![image](https://user-images.githubusercontent.com/67602108/235362512-bde5ea76-5140-450b-88cf-21fab21e50b9.png)|
|![image](https://user-images.githubusercontent.com/67602108/235362355-c3738f50-4297-4a16-a7de-ca30979df896.png)||
> [feature] 마이 랭킹 추가 및 아무도 흔들지 않았을 때 텍스트 추가

- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- x위가 없을 때 x위가 없어요 추가입니다
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://user-images.githubusercontent.com/67602108/235370469-cdc2db6e-a21f-4990-9bf8-a0a2170680b3.png)|
> [feature] 랭킹 없을 때 아직 x위가 없어요 추가

- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- 플랫폼 랭킹 추가입니다
|이전 화면|변경된 화면|
|---|---|
|input your previous image|
> [feature] 플랫폼 랭킹 추가입니다

- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnModeController.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeEffect.kt
- 당근 흔들 때 Effect 효과
https://user-images.githubusercontent.com/47407541/235731644-9e1f7f1b-5644-4474-b26c-a74a6d9db42c.mp4
close #322  🦕
> [Feature] 당근 흔들 때 Effect 효과

- app/build.gradle
- app/src/main/java/com/mashup/MashUpApplication.kt
- app/src/main/java/com/mashup/di/NetworkModule.kt
- core/network/src/main/java/com/mashup/network/Response2.kt
- dependencies.gradle
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/DanggnDao.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
- 플리퍼 넣었습니다
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://user-images.githubusercontent.com/67602108/235972266-c8cf0391-f29f-49ce-8788-0f1138183332.png)|
close #328 🦕
> [feature] 플리퍼 추가 (network, layout, logging)

- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
- 당근 흔들기 화면이랑 랭킹 UI 스크롤 연결
close #326 🦕
> 🐛 #326 당근 흔들기 + 랭킹 스크롤 연결

- app/src/main/java/com/mashup/ui/main/popup/MainBottomPopup.kt
- onCreate에서 viewed api 호출하기
화면 변경없음
close #332  🦕
> 🛠 #332 viewed api 호출 onCreate에서 하기

- app/src/main/java/com/mashup/ui/danggn/DanggnInfoActivity.kt
- app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
- app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
- core/common/src/main/res/anim/slide_in_left.xml
- core/common/src/main/res/anim/slide_in_right.xml
- 화면 전환 애니메이션 적용!
앱 초기 실행할때는 전환 애니메이션 시 검은 화면이 잠깐 보이는 현상이 있음 ㅜㅜㅜ
close #334  🦕
> [Fix] 화면 전환 애니메이션 적용

- core/common/src/main/AndroidManifest.xml
- core/common/src/main/java/com/mashup/core/common/extensions/ContextExt.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnGameController.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeContent.kt
- 당근 흔들기 진동 추가하기
화면 변경 없음
close #343  🦕
> [Feature] 당근 흔들기 진동 추가

- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- 당근 흔들면 화면 상단으로 올리기
- onShakeDevice 감지되면 화면 스크롤이 상단으로 올라감
close #348 🦕
> [Feature] 당근 흔들면 화면 상단으로 올리기

- feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeEffect.kt
- key function 사용해서 effect 그리기. 기존 포지션 방식으로 사용할 경우, 특정 케이스에서 나타난지 1초도 안되서 사라지는 당근이 발생함
- 화면에 당근이 벗어나져 그려지는 현상 방지
화면 변경없음
close #354  🦕
> [Fix] 당근 이펙트 개선

- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- 당근 화면 스크롤 할 때 디용거리는거 없애기. 👀
close #362  🦕
> [Feature] 컴포즈 VerticalScroll 할 때 생기는 overScroll effect 없애기

- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- 진동 세기 변경
일반 당근: 40
황금 당근: 255
화면 변경없음
close #364  🦕
> [Refactoring] 진동 세기 변경

- app/src/main/java/com/mashup/constant/ExtraConstant.kt
- app/src/main/java/com/mashup/service/PushLinkType.kt
- app/src/main/java/com/mashup/ui/main/MainActivity.kt
- app/src/main/java/com/mashup/ui/main/MainViewModel.kt
- app/src/main/java/com/mashup/ui/splash/SplashActivity.kt
- MyPage 딥링크 추가하기
화면 변경 없음
close #360  🦕
> [Feature] myPage 딥링크 추가하기

- app/src/main/java/com/mashup/ui/main/popup/MainBottomPopup.kt
> [Fix] 팝업 하단 짤림 현상

- core/ui/src/main/java/com/mashup/core/ui/widget/MashUpTextField.kt
- 매셥 텍스트 필드 구현했슴다
- compose ㄹㅇ 초보라서 피드백 많이 원함.
|이전 화면|변경된 화면|
|---|---|
> [refactoring] mashup textfield 구현

- .github/workflows/android.yml
- sample
|이전 화면|변경된 화면|
|---|---|
> [feature] ci 추가

- .github/workflows/android.yml
- app/build.gradle
- app/src/main/java/com/mashup/network/interceptor/BaseInterceptor.kt
- 암호화 기능 추가입니다
화면 변경 없음
close #390  🦕
> [feature] 암호화 기능 추가

- core/ui/src/main/java/com/mashup/core/ui/widget/MashupTabRow.kt
- tabRow file rename & 로직 오류 수정
close #387 🦕
> [Feature] tabRow 오류 수정 & rename

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mashup/ui/main/MainActivity.kt
- app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
- app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
- core/common/src/main/java/com/mashup/core/common/utils/PermissionHelper.kt
- core/common/src/main/java/com/mashup/core/common/widget/CommonDialog.kt
- dependencies.gradle
- target, compile SDK 33으로 올리기
- 푸시 권한 요청 추가
고민..
- CommonDialog가 Dim이 안된다는 것을 발견했는데 해결 방법을 모르겠어요 흑흗..
|권한 거부시 다이얼로그|
|---|
|<img width="231" alt="image" src="https://github.com/mash-up-kr/mashup_Android/assets/33657541/f6032379-2932-4a43-bf5e-460f517a1d50">|
close #382 🦕
> [Feature] Android SDK 33 대응하기

- app/build.gradle
- app/src/main/java/com/mashup/service/MashUpFirebaseMessagingService.kt
- app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
- build.gradle
- core/common/build.gradle
- core/datastore/build.gradle
- core/model/build.gradle
- core/network/build.gradle
- core/testing/build.gradle
- core/ui/build.gradle
- dependencies.gradle
- feature/danggn/build.gradle
- feature/setting/build.gradle
- compose를 제외한 기본 의존성 버전 업
화면 변경 없음
> [Feature] common dependencies 버전 업

- app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnWeeklyRankingContent.kt
- sample
- figma link
: https://www.figma.com/file/kxgTs6r19oJz6ipQGYm83d/%EB%A7%A4%EC%89%AC%EC%97%85-%EC%95%B1?type=design&node-id=1649-26304&mode=design&t=KMoRnPpnsbCJbnHG-0
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://github.com/mash-up-kr/mashup_Android/assets/67602108/14be10b2-67dc-45fd-8b84-decac40c3e12)|
> [feat] viewModel 데이터 연동

- app/src/main/java/com/mashup/ui/danggn/DanggnRoundSelectorDialog.kt
- app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
- app/src/main/java/com/mashup/ui/main/MainActivity.kt
- app/src/main/java/com/mashup/ui/main/popup/MainBottomPopup.kt
- core/ui/src/main/java/com/mashup/core/ui/typography/Typography.kt
- core/ui/src/main/java/com/mashup/core/ui/widget/bottomsheet/BottomSheet.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/round/DanggnRoundScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ui/DanggnUpdateScreen.kt
- 당근 회차 팝업 구현하기
TODO
- currentRound 셋팅하기
- figma link
: https://www.figma.com/file/kxgTs6r19oJz6ipQGYm83d/%EB%A7%A4%EC%89%AC%EC%97%85-%EC%95%B1?type=design&node-id=1649-26432&mode=design&t=XDteDSJ44UbhFsKn-4
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://github.com/mash-up-kr/mashup_Android/assets/33657541/2de4df5d-cd66-4ab7-bc93-7cd366b60779)|
close #413  🦕
> [Feature] 당근 회차 팝업 구현하기

- app/src/main/res/values-v26/themes.xml
- app/src/main/res/values-v27/themes.xml
- app/src/main/res/values/themes.xml
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnFirstPlaceBottomPopup.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardPopup.kt
- 리워드로 공지 등록하는 플로우 및 UI 개발
https://github.com/mash-up-kr/mashup_Android/assets/47407541/4f4fa019-b2a0-45c7-ab35-07c36ba5f41b
- 도와줘유.. 키보드 켜면 바텀시트가 끝까지 안올라와유..
> [Feature] 리워드로 공지 등록하는 플로우 및 UI 개발

- feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnRankingSingleRoundCheckResponse.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardContent.kt
- Reward UI 구현
- figma link
:https://www.figma.com/file/kxgTs6r19oJz6ipQGYm83d/%EB%A7%A4%EC%89%AC%EC%97%85-%EC%95%B1?type=design&node-id=1649-25757&mode=design&t=1s5AoH6BTxSdEoGM-4
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://github.com/mash-up-kr/mashup_Android/assets/33657541/c9c1314d-7b49-4d5e-8672-ea8d283cb330)
|
close #406  🦕
> [Feature] DanggnRankingReward UI 구현

- app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
- core/datastore/src/main/java/com/mashup/datastore/data/repository/UserPreferenceRepository.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnWeeklyRankingContent.kt
> [Feature] 당근 회차 선택 로직 추가하기

- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
- 당근 탭 UI 수정
- figma link
: https://www.figma.com/file/kxgTs6r19oJz6ipQGYm83d/%EB%A7%A4%EC%89%AC%EC%97%85-%EC%95%B1?type=design&node-id=1649-26304&mode=design&t=sLgHwvTkK79PdfuL-4
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://github.com/mash-up-kr/mashup_Android/assets/33657541/f6093c18-9efc-4c60-a706-ab905142e03c)|
> [Feature] 당근 탭 UI 수정

- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnWeeklyRankingContent.kt
- sample
몇일 남았는지 보여줍니다
- figma link
:
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://github.com/mash-up-kr/mashup_Android/assets/67602108/57f9a0cc-ebd9-4662-b6ba-6f897cde7783)|
타이머 구현은 내일 해볼게요 ㅠ
> [feat] 몇일 남았는지 표시

- feature/danggn/build.gradle
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/DanggnDao.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnRankingRewardCommentRequest.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnFirstPlaceBottomPopup.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardPopup.kt
- 당근 지난 회차 1등 리워드로 등록하고 싶은 comment POST
---
> [Feature] 당근 지난 회차 1등 리워드로 등록하고 싶은 comment POST

- app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnRankingSingleRoundCheckResponse.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardContent.kt
- DanggnRewardUi 연결
- figma link
:
화면 변경 없음
> [Feature] DanggnRewardUi 연결

- core/common/src/main/java/com/mashup/core/common/extensions/FlowExtention.kt
- core/common/src/main/java/com/mashup/core/common/utils/TimerUtils.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnRankingSingleRoundCheckResponse.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnWeeklyRankingContent.kt
- sample
타이머 기능 넣었습니다
민욱이의 dateDiff 보고 진입시에 자동으로 타이머 시작하는 로직은 추가되어야 합니다.
- figma link
: https://www.figma.com/file/kxgTs6r19oJz6ipQGYm83d/%EB%A7%A4%EC%89%AC%EC%97%85-%EC%95%B1?type=design&node-id=2-6&mode=design&t=YLjpU4LdetUrG0SI-0
|이전 화면|변경된 화면|
|---|---|
|input your previous image|[영상.webm](https://github.com/mash-up-kr/mashup_Android/assets/67602108/b2824ec6-f749-407d-9bb8-6e1a45c6a690)
|
> [feat] 타이머 기능 구현

- core/common/src/main/java/com/mashup/core/common/extensions/CoroutineExtention.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- suspendRunCatching 추가
화면 변경 없음
> 🧸 suspendRunCatching 추가

- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnFirstPlaceBottomPopup.kt
- 빠진 Hilt 어노테이션 추가
- 나는 바보다. 나는 바보다. 나는 바보다.
> [FIX] 빠진 Hilt 어노테이션 추가

- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardContent.kt
- firstPlace flag 보는 위치 수정
- figma link
:
|이전 화면|변경된 화면|
|---|---|
> [Fix] 리워드 UI 로직 수정

- core/common/src/main/java/com/mashup/core/common/utils/TimerUtils.kt
- core/common/src/main/java/com/mashup/core/common/utils/Tuples.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- Timer 설정 코드 오류 수정
- figma link
:
|이전 화면|변경된 화면|
|---|---|
> [Fix] Timer 설정 코드 오류 수정

- app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnLastRoundFirstPlaceScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnFirstPlaceBottomPopup.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardPopup.kt
> [FIX] 이전 회차 1등 축하문구 변경

- app/src/main/java/com/mashup/ui/signup/fragment/auth/SignUpAuthViewModel.kt
- id 중복 체크 로직 오류 수정
- figma link
:
|이전 화면|변경된 화면|
|---|---|
> 🐛 Id 중복 체크 로직 오류 수정

- app/src/main/java/com/mashup/service/PushLinkType.kt
- app/src/main/java/com/mashup/ui/login/LoginActivity.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
- feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardNoticeScreen.kt
- 당근 나머지 에러 해결
- figma link
:
|이전 화면|변경된 화면|
|---|---|
> [Fix] 당근 나머지 에러 해결
